//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian.Menta.WF.Logger.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guardian.Menta.CRM.Logger.Logger.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the connection string to use for logging messages, as configured in the connection strings section..
        /// </summary>
        internal static string DynamicsCrm2011TraceListenerDataCrmConnectionStringNameDescription {
            get {
                return ResourceManager.GetString("DynamicsCrm2011TraceListenerDataCrmConnectionStringNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm Connection String Name.
        /// </summary>
        internal static string DynamicsCrm2011TraceListenerDataCrmConnectionStringNameDisplayName {
            get {
                return ResourceManager.GetString("DynamicsCrm2011TraceListenerDataCrmConnectionStringNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logging target listener that sends log messages to a specified Microsoft Dynamics CRM 2011 organisation using a crm connection string configured in the connection strings section..
        /// </summary>
        internal static string DynamicsCrm2011TraceListenerDataDescription {
            get {
                return ResourceManager.GetString("DynamicsCrm2011TraceListenerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics CRM 2011 Trace Listener.
        /// </summary>
        internal static string DynamicsCrm2011TraceListenerDataDisplayName {
            get {
                return ResourceManager.GetString("DynamicsCrm2011TraceListenerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Log Message Formatter to use to format log messages written to the Microsoft Dynamics CRM 2011 organisation..
        /// </summary>
        internal static string DynamicsCrm2011TraceListenerDataFormatterDescription {
            get {
                return ResourceManager.GetString("DynamicsCrm2011TraceListenerDataFormatterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter.
        /// </summary>
        internal static string DynamicsCrm2011TraceListenerDataFormatterDisplayName {
            get {
                return ResourceManager.GetString("DynamicsCrm2011TraceListenerDataFormatterDisplayName", resourceCulture);
            }
        }
    }
}
